INFO: 2021-01-15 10:24:47,843: main() 'Using profile folder /home/frank/.config/variety/'
INFO: 2021-01-15 10:24:47,896: perform_upgrade() 'Last run version was 0.8.5 or earlier, current version is 0.8.5'
INFO: 2021-01-15 10:24:50,804: process_command() 'Received command: []'
INFO: 2021-01-15 10:24:50,805: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2021-01-15 10:24:50,881: start() 'Using data_path /usr/share/variety'
INFO: 2021-01-15 10:24:50,882: load() 'Jumble loading'
INFO: 2021-01-15 10:24:50,882: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/__init__.py'
INFO: 2021-01-15 10:24:50,902: _walk_modules() 'Jumble loading module in FortuneSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/FortuneSource.py'
INFO: 2021-01-15 10:24:50,905: load() 'Jumble found plugin class: <class 'FortuneSource.FortuneSource'>: {'name': 'UNIX fortune program', 'description': 'Displays quotes using the UNIX fortune program. You may want to install additional fortune packs, e.g. fortunes-bofh-excuses.', 'author': 'Dan Jones', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,907: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/GoodreadsSource.py'
INFO: 2021-01-15 10:24:50,930: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': 'Fetches quotes from Goodreads.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,931: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/LocalFilesSource.py'
INFO: 2021-01-15 10:24:50,933: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,934: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/__init__.py'
INFO: 2021-01-15 10:24:50,936: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/QuotationsPageSource.py'
INFO: 2021-01-15 10:24:50,938: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': 'Fetches quotes from TheQuotationsPage.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,939: _walk_modules() 'Jumble loading module in UrbanDictionarySource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/UrbanDictionarySource.py'
INFO: 2021-01-15 10:24:50,940: load() 'Jumble found plugin class: <class 'UrbanDictionarySource.UrbanDictionarySource'>: {'name': 'Urban Dictionary', 'description': 'Displays definitions from Urban Dictionary', 'author': 'James Miller', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,942: _walk_modules() 'Jumble loading module in UnsplashConfigurableSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/UnsplashConfigurableSource.py'
INFO: 2021-01-15 10:24:50,946: load() 'Jumble found plugin class: <class 'UnsplashConfigurableSource.UnsplashConfigurableSource'>: {'name': 'UnsplashConfigurableSource', 'description': 'Configurable source for fetching photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,947: _walk_modules() 'Jumble loading module in BingDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py'
INFO: 2021-01-15 10:24:50,949: load() 'Jumble found plugin class: <class 'BingDownloader.BingDownloader'>: {'name': 'BingDownloader', 'description': 'Bing Photo of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,949: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/__init__.py'
INFO: 2021-01-15 10:24:50,950: _walk_modules() 'Jumble loading module in APODDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py'
INFO: 2021-01-15 10:24:50,951: load() 'Jumble found plugin class: <class 'APODDownloader.APODDownloader'>: {'name': 'APODDownloader', 'description': 'NASA Astro Pic of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,952: _walk_modules() 'Jumble loading module in WallhavenDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/WallhavenDownloader.py'
INFO: 2021-01-15 10:24:50,954: _walk_modules() 'Jumble loading module in WallhavenSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/WallhavenSource.py'
INFO: 2021-01-15 10:24:50,955: load() 'Jumble found plugin class: <class 'WallhavenSource.WallhavenSource'>: {'name': 'WallhavenSource', 'description': 'Configurable source for fetching images from Wallhaven.cc', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,956: _walk_modules() 'Jumble loading module in MediaRSSSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/MediaRSSSource.py'
INFO: 2021-01-15 10:24:50,961: load() 'Jumble found plugin class: <class 'MediaRSSSource.MediaRSSSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from MediaRSS feeds', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,961: _walk_modules() 'Jumble loading module in UnsplashDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/UnsplashDownloader.py'
INFO: 2021-01-15 10:24:50,962: load() 'Jumble found plugin class: <class 'UnsplashDownloader.UnsplashDownloader'>: {'name': 'UnsplashDownloader', 'description': 'High-resolution photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,962: _walk_modules() 'Jumble loading module in EarthviewDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py'
INFO: 2021-01-15 10:24:50,963: load() 'Jumble found plugin class: <class 'EarthviewDownloader.EarthviewDownloader'>: {'name': 'EarthviewDownloader', 'description': 'Google Earth View Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:50,963: _walk_modules() 'Jumble loading module in MediaRSSDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/MediaRSSDownloader.py'
INFO: 2021-01-15 10:24:50,964: _walk_modules() 'Jumble loading module in RedditDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/RedditDownloader.py'
INFO: 2021-01-15 10:24:50,966: _walk_modules() 'Jumble loading module in RedditSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/RedditSource.py'
INFO: 2021-01-15 10:24:50,967: load() 'Jumble found plugin class: <class 'RedditSource.RedditSource'>: {'name': 'RedditSource', 'description': 'Configurable source for fetching images from Reddit', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-01-15 10:24:51,130: log_options() 'Loaded options:'
INFO: 2021-01-15 10:24:51,130: log_options() 'change_enabled = True'
INFO: 2021-01-15 10:24:51,130: log_options() 'change_interval = 60'
INFO: 2021-01-15 10:24:51,131: log_options() 'change_on_start = True'
INFO: 2021-01-15 10:24:51,131: log_options() 'clipboard_enabled = False'
INFO: 2021-01-15 10:24:51,131: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2021-01-15 10:24:51,131: log_options() 'clipboard_use_whitelist = True'
INFO: 2021-01-15 10:24:51,131: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2021-01-15 10:24:51,131: log_options() 'clock_enabled = False'
INFO: 2021-01-15 10:24:51,131: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2021-01-15 10:24:51,131: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2021-01-15 10:24:51,131: log_options() 'configfile = /home/frank/.config/variety/variety.conf'
INFO: 2021-01-15 10:24:51,132: log_options() 'copyto_enabled = False'
INFO: 2021-01-15 10:24:51,132: log_options() 'copyto_folder = Default'
INFO: 2021-01-15 10:24:51,132: log_options() 'desired_color = [160, 160, 160]'
INFO: 2021-01-15 10:24:51,132: log_options() 'desired_color_enabled = False'
INFO: 2021-01-15 10:24:51,132: log_options() 'download_folder = /home/frank/.config/variety/Downloaded'
INFO: 2021-01-15 10:24:51,132: log_options() 'download_preference_ratio = 0.9'
INFO: 2021-01-15 10:24:51,132: log_options() 'favorites_folder = /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers'
INFO: 2021-01-15 10:24:51,132: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2021-01-15 10:24:51,132: log_options() 'fetched_folder = /home/frank/.config/variety/Fetched'
INFO: 2021-01-15 10:24:51,132: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2021-01-15 10:24:51,133: log_options() 'icon = Light'
INFO: 2021-01-15 10:24:51,133: log_options() 'lightness_enabled = False'
INFO: 2021-01-15 10:24:51,133: log_options() 'lightness_mode = 0'
INFO: 2021-01-15 10:24:51,133: log_options() 'min_rating = 4'
INFO: 2021-01-15 10:24:51,133: log_options() 'min_rating_enabled = False'
INFO: 2021-01-15 10:24:51,133: log_options() 'min_size = 80'
INFO: 2021-01-15 10:24:51,133: log_options() 'min_size_enabled = False'
INFO: 2021-01-15 10:24:51,133: log_options() 'quota_enabled = True'
INFO: 2021-01-15 10:24:51,133: log_options() 'quota_size = 1000'
INFO: 2021-01-15 10:24:51,133: log_options() 'quotes_authors = '
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_bg_opacity = 55'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_change_enabled = False'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_change_interval = 300'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_disabled_sources = ['Urban Dictionary']'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_enabled = False'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_favorites_file = /home/frank/.config/variety/favorite_quotes.txt'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_hpos = 100'
INFO: 2021-01-15 10:24:51,134: log_options() 'quotes_max_length = 250'
INFO: 2021-01-15 10:24:51,135: log_options() 'quotes_tags = '
INFO: 2021-01-15 10:24:51,135: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2021-01-15 10:24:51,135: log_options() 'quotes_text_shadow = False'
INFO: 2021-01-15 10:24:51,135: log_options() 'quotes_vpos = 40'
INFO: 2021-01-15 10:24:51,135: log_options() 'quotes_width = 70'
INFO: 2021-01-15 10:24:51,135: log_options() 'safe_mode = False'
INFO: 2021-01-15 10:24:51,135: log_options() 'slideshow_custom_enabled = False'
INFO: 2021-01-15 10:24:51,135: log_options() 'slideshow_custom_folder = /home/frank/Pictures'
INFO: 2021-01-15 10:24:51,135: log_options() 'slideshow_downloads_enabled = False'
INFO: 2021-01-15 10:24:51,135: log_options() 'slideshow_fade = 0.4'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_favorites_enabled = True'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_mode = Fullscreen'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_monitor = All'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_pan = 0.05'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_seconds = 6.0'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_sort_order = Random'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_sources_enabled = True'
INFO: 2021-01-15 10:24:51,136: log_options() 'slideshow_zoom = 0.2'
INFO: 2021-01-15 10:24:51,136: log_options() 'smart_enabled = False'
INFO: 2021-01-15 10:24:51,136: log_options() 'smart_notice_shown = False'
INFO: 2021-01-15 10:24:51,137: log_options() 'smart_register_shown = False'
INFO: 2021-01-15 10:24:51,137: log_options() 'sources = [[True, 'favorites', 'The Favorites folder'], [False, 'fetched', 'The Fetched folder'], [False, 'folder', '/usr/share/backgrounds'], [False, 'flickr', 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [False, 'apod', "NASA's Astronomy Picture of the Day"], [False, 'bing', 'Bing Photo of the Day'], [False, 'earthview', 'Google Earth View Wallpapers'], [False, 'unsplash', 'High-resolution photos from Unsplash.com']]'
INFO: 2021-01-15 10:24:51,137: log_options() 'stats_enabled = True'
INFO: 2021-01-15 10:24:51,137: log_options() 'stats_notice_shown = False'
INFO: 2021-01-15 10:24:51,137: log_options() 'sync_enabled = True'
INFO: 2021-01-15 10:24:51,137: log_options() 'use_landscape_enabled = True'
INFO: 2021-01-15 10:24:51,137: reload_config() 'No need to clear prepared queue'
INFO: 2021-01-15 10:24:51,137: update_indicator() 'Setting file info to: /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Verdonschlucht_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:24:51,357: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 60'
INFO: 2021-01-15 10:24:51,357: update_indicator() 'Setting file info to: /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Verdonschlucht_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:24:51,359: regular_change_thread() 'regular_change thread running'
INFO: 2021-01-15 10:24:51,359: prepare_thread() 'Prepare thread running'
INFO: 2021-01-15 10:24:51,360: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2021-01-15 10:24:51,360: prepare_thread() 'Preparing some images'
INFO: 2021-01-15 10:24:51,365: update_indicator_icon() 'Creating indicator'
WARNING: 2021-01-15 10:24:51,374: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2021-01-15 10:24:51,375: create_indicator() 'indicator backend: AppIndicator3'
INFO: 2021-01-15 10:24:51,393: set_from_theme_icon() 'Showing indicator icon variety-indicator from GTK theme'
INFO: 2021-01-15 10:24:51,457: do_set_wp() 'Calling do_set_wp with /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Verdonschlucht_Desktop_1920x1080.jpg, time: 1610677491.4577048'
INFO: 2021-01-15 10:24:51,469: update_indicator() 'Setting file info to: /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Verdonschlucht_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:24:52,395: prepare_thread() 'After search prepared buffer contains 32 images'
INFO: 2021-01-15 10:24:54,011: reload() 'Reloading preferences dialog'
INFO: 2021-01-15 10:24:54,396: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-01-15 10:24:56,359: set_wallpaper() 'Calling set_wallpaper with /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Aletschgletscher_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:24:56,360: prepare_thread() 'Prepared buffer contains 31 images'
INFO: 2021-01-15 10:24:56,361: do_set_wp() 'Calling do_set_wp with /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Aletschgletscher_Desktop_1920x1080.jpg, time: 1610677496.3614657'
INFO: 2021-01-15 10:24:56,372: update_indicator() 'Setting file info to: /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Aletschgletscher_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:24:58,362: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-01-15 10:25:11,382: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-01-15 10:25:21,514: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f24325905e0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f24325905e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f24325905e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-01-15 10:25:51,549: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-01-15 10:25:56,573: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2432590df0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2432590df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2432590df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-01-15 10:25:56,797: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2021-01-15 10:25:56,798: set_wallpaper() 'Calling set_wallpaper with /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Costa_Rica_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:25:56,799: do_set_wp() 'Calling do_set_wp with /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Costa_Rica_Desktop_1920x1080.jpg, time: 1610677556.7989807'
INFO: 2021-01-15 10:25:56,799: prepare_thread() 'Prepared buffer contains 30 images'
INFO: 2021-01-15 10:25:56,811: update_indicator() 'Setting file info to: /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Costa_Rica_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:25:58,801: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-01-15 10:26:26,606: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-01-15 10:26:31,665: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2432584100>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2432584100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2432584100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-01-15 10:26:57,241: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2021-01-15 10:26:57,242: set_wallpaper() 'Calling set_wallpaper with /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Thailand_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:26:57,242: prepare_thread() 'Prepared buffer contains 29 images'
INFO: 2021-01-15 10:26:57,243: do_set_wp() 'Calling do_set_wp with /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Thailand_Desktop_1920x1080.jpg, time: 1610677617.2438645'
INFO: 2021-01-15 10:26:57,254: update_indicator() 'Setting file info to: /home/frank/.config/variety/Favorites/Marmotamaps_Wallpapers/Marmotamaps_Wallpaper_Thailand_Desktop_1920x1080.jpg'
INFO: 2021-01-15 10:26:59,244: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-01-15 10:27:01,698: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-01-15 10:27:06,759: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2432499670>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2432499670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2432499670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
